import pygame

# tamanho do jogo
COLUNAS = 10
LINHAS = 20
CELULA = 20
LARGURA_JOGO, ALTURA_JOGO = COLUNAS * CELULA, LINHAS * CELULA

# tamanho do display ao lado
LARGURA_LADO = 200
ALTURA_PECAS = 0.7
ALTURA_PONTUACAO = 1 - ALTURA_PECAS

# janela
PADDING = 20
LARGURA_JANELA = LARGURA_JOGO + LARGURA_LADO + PADDING * 3
ALTURA_JANELA = ALTURA_JOGO + PADDING * 2

# cores!!
CIANO = '#0EE3E7'
AZUL = '#1208D6'
VERDE = '#27FF00'
AMARELO = '#FFDD20'
LARANJA = '#FF5D00'
VERMELHO = '#F00808'
ROXO = '#9C00FB'
CINZA = '#1B1B1B'
COR_LINHA = '#FFFFFF'