import pygame

# tamanho do jogo
COLUNAS = 10
LINHAS = 20
CELULA = 20
LARGURA_JOGO, ALTURA_JOGO = COLUNAS * CELULA, LINHAS * CELULA

# tamanho do display ao lado
LARGURA_LADO = 200
ALTURA_PECAS = 0.7
ALTURA_PONTUACAO = 1 - ALTURA_PECAS

# janela
PADDING = 20
LARGURA_JANELA = LARGURA_JOGO + LARGURA_LADO + PADDING * 3
ALTURA_JANELA = ALTURA_JOGO + PADDING * 2